name: Docker Hub Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          cache: yarn
          cache-dependency-path: DashboardFrontend/yarn.lock
      - name: Restore NPM Packages
        run: yarn install --frozen-lockfile
        working-directory: DashboardFrontend
        
      - name: Build Frontend
        run: yarn build
        working-directory: DashboardFrontend
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/rimionship-server
          tags: latest
          registry: docker.io
          dockerfile: RimionshipServer/Dockerfile
